### ISSUE TITLE
run has error

### ISSUE THREAD

**Issue by wlxklyh** [ChinaZeng/SurfaceRecodeDemo#1]
java.nio.BufferOverflowException
	at java.nio.DirectByteBuffer.put(DirectByteBuffer.java:291)
	at java.nio.ByteBuffer.put(ByteBuffer.java:642)
	at com.zzw.live.encodec.BaseVideoEncoder.putPcmData(BaseVideoEncoder.java:182)
	at com.zzw.live.RecodeActivity$PutPcmThread.run(RecodeActivity.java:123)

**Comment by webbrain-one** [comment]
Hi! I’ve opened PR #2 (https://github.com/ChinaZeng/SurfaceRecodeDemo/pull/2) to fix this issue. It resolves the `BufferOverflowException` reported in `BaseVideoEncoder.putPcmData` so the app can run without crashing.
